### ISSUE TITLE
How do you make this work?

### ISSUE THREAD

**Issue by mistermantas** [bash/millionaire#1]
Add a README, please! I’d love to check this out, want to do something for my school as well.

**Comment by janhohenheim** [comment]
hehe, we can take a look at it. It's been a while since we touched it, though :)

**Comment by tautropfli** [comment]
It's nice to see that someone is still interested in this project 😉 ...

I have added build/setup instructions to the readme in https://github.com/bash/millionaire/commit/6dd388d8eaf0bc010f283dc6c46a983c4f442e5f.
I'm closing this issue for now. Feel free to reopen if I missed something.
